### ISSUE TITLE
The borderRadius of different images is inconsistent on iOS

### ISSUE THREAD

**Issue by yang1206** [duguyihou/react-native-turbo-image#233]
When rendering a batch of different images with the same size and the same borderRadius value, I find that the borderRadius of some images is inconsistent with the expected value, while others are correct. I am confused. Is this behavior expected?

**Comment by duguyihou** [comment]
hey @yang1206 can you provide more info? like the url and the reproduce steps.

**Comment by yang1206** [comment]
Thanks for the reply, I was just missing the resize attribute and everything worked fine after adding it. Thanks for building this library, it's great!

**Comment by duguyihou** [comment]
hey @yang1206 , do you mind sharing the part of the code? It may not be related to `resize`.  `resize` is for downsampling. 
I made some changes to `TurboImageScreen.ts`
```ts
<TurboImage src={item.url} style={styles.card} borderRadius={20} />
```
It shows the border correctly.

https://github.com/duguyihou/react-native-turbo-image/assets/9347790/e09a5596-cb1c-498e-8a21-b2c371ea91a8

**Comment by yang1206** [comment]
```ts
  <TurboImage
     accessibilityIgnoresInvertColors
     src={image.url}
     // resize={150}
     resizeMode="cover"
     borderRadius={12}
     style={{
       width: 150,
       height: 150,
     }}
   />
```



```
const images = [
https://p1.music.126.net/U8geVbDFLBRxwiPOzYjPUg==/109951169659830623.jpg,
https://p1.music.126.net/1qgNaqQAoOY3NatkGX1EDQ==/109951169663417311.jpg,
https://p1.music.126.net/w1A7-Eqx26C0-ANXd3NolA==/109951169646542385.jpg,
https://p1.music.126.net/UxpCkRtaza_E9gzmHmaUuQ==/109951169633594987.jpg,
https://p1.music.126.net/BblShx_E3n3FICm4WHr49A==/109951169620893803.jpg,
https://p1.music.126.net/6kZ5jDwv4p_BpcVbGT6dVQ==/109951169593337636.jpg,
https://p1.music.126.net/NZOnDqpyTA45AWL8kGsqxg==/109951169679537837.jpg,
https://p1.music.126.net/OMwSNgFHEOy067Cu8_0XeQ==/109951169548628184.jpg,
https://p1.music.126.net/mtHhRajqBY6MGmLiBL4EVA==/109951169549020830.jpg
]
```

**Comment by duguyihou** [comment]
@yang1206 It does have border radius without `resize`.  The reason you see it is not consistent is because  the images' sizes are not the same.

<img width="760" alt="image" src="https://github.com/duguyihou/react-native-turbo-image/assets/9347790/1a8b19ae-dc3d-437f-a07e-ecf143dc7b8a">
<img width="618" alt="image" src="https://github.com/duguyihou/react-native-turbo-image/assets/9347790/8b6f81af-2046-4582-bc01-038ae68bac28">

If you try to set a large value to border radius, it will show different radius.
```ts
<TurboImage src={item.url} style={styles.card} borderRadius={80} />
```
<img width="321" alt="image" src="https://github.com/duguyihou/react-native-turbo-image/assets/9347790/96a4ce44-b048-4d47-a4be-a056291d7588">

It is better to downsampling the image when trying to download a hug image. That's why `resize` solve the problem. It 
scales the image to a specified size.

**Comment by yang1206** [comment]
> It is better to downsampling the image when trying to download a hug image. That's why `resize` solve the problem. It
> scales the image to a specified size.

Wow, Thank you for your guidance!
